[package]
name = "fletch-site"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
axum = {version = "0.6.18", features = ["ws"]}
liquid = "0.26.1"
notify = "5.1.0"
quick-xml = { version = "0.28.2", features = ["serialize"] }
railwind = "0.1.5"
serde = "1.0.162"
serde_json = "1.0.96"
tera = "1.19.0"
tokio = {version = "1.28.0", features = ["full"]}
tower-http = {version = "0.4.0", features = ["fs"]}
